{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-snowflakeauth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/snowflakeauth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/snowflakeauth/snowflakeauth_{{ version }}.tar.gz
  sha256: 880d90a6dfc2638f3800a5316624b93748905002822cb45d8e45c290d4e06b08

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpptoml
    - r-cli
    - r-curl
    - r-jose
    - r-jsonlite
    - r-openssl
    - r-rlang
  run:
    - r-base
    - r-rcpptoml
    - r-cli
    - r-curl
    - r-jose
    - r-jsonlite
    - r-openssl
    - r-rlang

test:
  commands:
    - $R -e "library('snowflakeauth')"           # [not win]
    - "\"%R%\" -e \"library('snowflakeauth')\""  # [win]

about:
  home: https://posit-dev.github.io/snowflakeauth/, https://github.com/posit-dev/snowflakeauth
  license: MIT
  summary: Authentication helpers for 'Snowflake'. It provides compatibility with authentication approaches supported by the 'Snowflake Connector for Python' <https://pypi.org/project/snowflake-connector-python> and the 'Snowflake CLI' <https://pypi.org/project/snowflake-cli>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
